[package]
name = "navi"
version = "2.18.0"
authors = ["Denis Isidoro <denis_isidoro@live.com>"]
edition = "2021"
description = "An interactive cheatsheet tool for the command-line"
homepage = "https://github.com/denisidoro/navi"
documentation = "https://github.com/denisidoro/navi"
repository = "https://github.com/denisidoro/navi"
keywords = ["cheatsheets", "terminal", "cli", "tui", "shell"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = { repository = "denisidoro/navi", branch = "master" }

[dependencies]
regex = { version = "1.5.4", default-features = false, features = ["std", "unicode-perl"] }
clap = "3.0.0-beta.5"
crossterm = "0.22.1"
lazy_static = "1.4.0"
directories-next = "2.0.0"
walkdir = "2.3.1"
shellwords = "1.1.0"
anyhow = "1.0.60"
thiserror = "1.0.30"
strip-ansi-escapes = "0.1.1"
edit = "0.1.3"
remove_dir_all = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[lib]
name = "navi"
path = "src/lib.rs"

[[bin]]
name = "navi"
path = "src/bin/main.rs"
bench = false
